name       : paprefs
version    : 1.0
release    : 1
source     :
    - https://freedesktop.org/software/pulseaudio/paprefs/paprefs-1.0.tar.xz : ad12e47e2cf120533ffa04e622eb0f255786dfea64f19be5de5a2ba55e8ae778
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : PulseAudio Preferences
description: |
    PulseAudio Preferences (paprefs) is a simple GTK based configuration dialog for the PulseAudio sound server.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libpulse)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
