name       : paprefs
version    : 1.1
release    : 6
source     :
    - https://gitlab.freedesktop.org/pulseaudio/paprefs/-/archive/v1.1/paprefs-v1.1.tar.bz2 : 37a635bd0bd6523a8795e99ac6bd951d7272fe0019ffb2f5ddd0f24693f6eb83
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : PulseAudio Preferences
description: |
    PulseAudio Preferences (paprefs) is a simple GTK based configuration dialog for the PulseAudio sound server.
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libpulse)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
