name       : paprefs
version    : '1.0'
release    : 2
source     :
    - https://gitlab.freedesktop.org/pulseaudio/paprefs/-/archive/v1.0/paprefs-v1.0.tar.bz2 : 39db63ece3e37d2851dcd01b4dbe2c6921264e9e74ecd2de202c9b1215d5b8a4
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : PulseAudio Preferences
description: |
    PulseAudio Preferences (paprefs) is a simple GTK based configuration dialog for the PulseAudio sound server.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libpulse)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
